### ISSUE TITLE
Sentry errors grouped as same error

### ISSUE THREAD

**Issue by gabibeyer** [damianopetrungaro/golog#64]
Although different unhandled error are occurring, they're being read by sentry as the same stack trace: 
`*errors.errorString github.com/damianopetrungaro/golog/sentry in (*Writer).WriteEntry`

**Comment by damianopetrungaro** [comment]
Thanks @gabibeyer, will take a look into it ASAP!

**Comment by damianopetrungaro** [comment]
@gabibeyer a fix has been merged! Soon the release will be rolled out :D
